feat/go
dargstack/dargstack pull request #53
Opened 2022-11-28 22:22 UTC by azolus

started rewriting dargstack in Go 🥳

requires go 1.18

this should eliminate some of the bash-related problems with mac and windows, once it's done

todo: proper documentation, dargstack build and deploy commands, and leveraging the flexibility of the go-implementation to clean up some of the bash related idiosyncracies in the dargstack-architecture

2022-11-29 00:16 UTC, dargmuesli requested changes

2022-11-29 00:16 UTC, dargmuesli commented on .github/workflows/ci.yml
>      needs: shellcheck
```suggestion
    needs: golangci
```

2022-11-29 00:17 UTC, azolus commented on .github/workflows/ci.yml
>      needs: shellcheck
👍🏼

2022-12-21 12:57 UTC, azolus commented
I am putting this on hold, since I currently don't have time to finish this pr. Will get back to it next year.

2023-06-15 11:42 UTC, dargmuesli commented
Closing due to inactivity

2023-06-15 11:42 UTC, closed without merging